spring:
  data:
    mongodb:
      database: sample
      host: host.docker.internal
      port: 27017

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG